### ISSUE TITLE
[Q] how would you include pipes `|` in the list?

### ISSUE THREAD

**Issue by ninrod** [noctuid/evil-textobj-anyblock#9] opened 2016-11-22 09:12 UTC
In vim I used to use the `|` textobj all the time for markdown tables.

I am trying this with no success:

```elisp
(use-package evil-textobj-anyblock :ensure t
    :init
    (setq evil-textobj-anyblock-blocks '(("|" . "|")))
    :config
    (define-key evil-inner-text-objects-map "c" 'evil-textobj-anyblock-inner-block)
    (define-key evil-outer-text-objects-map "c" 'evil-textobj-anyblock-a-block))
```

how would I use your package to include pipes as a target for evil-textobj-anyblock?

ps: why do you have to insert double slashes `\\[` to escape the square brackets?

edit: I've just tested `("|" . "|")`, `("\|" . "\|")` and `("\\|" . "\\|")`. None worked.

**Comment by noctuid** [comment] 2016-11-30 02:10
I'll have to look into it. Just "|" should be correct. 

If you want to have a dedicated text object for them, you could do that instead though (if you haven't already):

```
(evil-define-text-object evil-inner-| (count &optional beg end type)
  (evil-select-paren "|" "|" beg end type count nil))
(evil-define-text-object evil-a-| (count &optional beg end type)
  (evil-select-paren "|" "|" beg end type count t))
(define-key evil-inner-text-objects-map "|" #'evil-inner-|)
(define-key evil-outer-text-objects-map "|" #'evil-a-|)
```

[This](http://stackoverflow.com/a/22418983/2744245) is handy for creating new text-objects as well (I think I may add it to general.el):
```
;; modified to be able to specify name and use `function'
(defmacro define-and-bind-text-object (name key start-regex end-regex)
  (let ((inner-name (make-symbol (concat "evil-inner-" name)))
        (outer-name (make-symbol (concat "evil-a-" name))))
    `(progn
       (evil-define-text-object ,inner-name (count &optional beg end type)
         (evil-select-paren ,start-regex ,end-regex beg end type count nil))
       (evil-define-text-object ,outer-name (count &optional beg end type)
         (evil-select-paren ,start-regex ,end-regex beg end type count t))
       (define-key evil-inner-text-objects-map ,key #',inner-name)
       (define-key evil-outer-text-objects-map ,key #',outer-name))))

(define-and-bind-text-object "pipe" "|" "|" "|")
```

**Comment by ninrod** [comment] 2016-11-30 07:58
@noctuid those are just amazing!

can I rewrite this macro to include seek forward as you did in anyblock?

**Comment by ninrod** [comment] 2016-11-30 08:24
With evil-textobj-anyblock, you've almost implemented what [wellle/targets.vim](https://github.com/wellle/targets.vim#examples) does. I miss dearly this functionality:

```txt
cursor position │    .....................
buffer line     │    This is example text (with a pair of parentheses).
selection       │                          └───────── cib ──────────┘

```

**Comment by ninrod** [comment] 2016-11-30 08:38
@noctuid, what's exactly the purpose of including name in the macro? 
because the macro is working correctly, but when I `M-x describe-function`-> `evil-inner-pipe` nothing shows up. Shouldn't the evil-inner-pipe function be created after an execution of the macro?

**Comment by ninrod** [comment] 2016-11-30 09:32
wait, Ive just defined (this was a long minor pain point for me, comming from vim, so thank you very much) a new text object for square brackets,
and one for pipes:

```elisp
(define-and-bind-text-object "squarebrackets" "r" "\\[" "\\]")
(define-and-bind-text-object "pipe" "|" "|" "|")
```

and seeking forward already *is* working correctly for the square brackets, put not for the pipes.
seeking also works for quotes and doubles quotes in stock evil, but not with round brackets

note that `ci[` does not seek, but my new textobj `cir` seeks, just from using your macro.

I wonder what is going on?

update: now i have defined also `(define-and-bind-text-object "squarebrackets" "c" "{" "}")`

and `cic` is seeking forward to a `{curly brackets}`. It is wonderful that is already working for those textobjs, but I wonder why it is working, so we could reproduce this seeking behaviour to all the textobjs.

**Comment by noctuid** [comment] 2016-11-30 10:53
Yeah I was thinking of porting targets.vim and obsoleting this plugin.

The name arg is just so you can choose the name of the function. Nothing shows up for describe function because there is no docstring. I'll create a better version that automatically generates a docstring (that can optionally be overridden) and allows alternatively using `evil-range` instead of `evil-select-paren` to create the text object.

> note that ci[ does not seek, but my new textobj cir seeks, just from using your macro.

If you define it like `(define-and-bind-text-object "squarebrackets" "r" ?\[ ?\])`, it won't seek (that's how it's defined by default). The reason the pipe text object isn't seeking is because the the open/close character is the same (`|`).

I'd have to look at `evil-select-paren` to find out exactly what is going on (seems like it has to do with `evil-up-block`'s behavior; `evil-up-paren` is probably the reason seeking doesn't work for `[` normally). I have on [open issue](https://bitbucket.org/lyro/evil/issues/574/seek-forward-when-evil-select-paren-fails) for evil about seeking, but looking at this, I think it's obsolete. I haven't decided whether I want to mess with `evil-select-paren` directly or just implement seeking on top of it (like I do in this plugin). Either way, I'll make a way of creating text objects that seek regardless of whether the open/close regexp is the same. I may not need to do anything. The solution may just be to use `evil-select-quote`, but I seem to remember there being problems for non-quotes (may be totally wrong about that).

**Comment by noctuid** [comment] 2016-11-30 11:23
Actually `evil-select-quote` seems to work fine for pipes and should probably be used instead. The issue is that when the opening and closing delimiters are the same, there is the potential for ambiguity:
```
| |
point here (should seek forward or select this line?)
| |
```

`evil-select-quote` is pretty smart. The problem I was thinking about is if you have have pipe as a character (`?|`), it will break the balance, and the text object will stop working correctly. However it looks like you can escape it and it like `?\|` and have it work the same. This should seek correctly:

```
(evil-define-text-object evil-inner-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count nil))

(evil-define-text-object evil-a-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count t))
```

I'll modify the macro to automatically determine whether to use `evil-select-paren` or `evil-select-quote`, so seeking should always work then.

**Comment by ninrod** [comment] 2016-11-30 15:39
@noctuid, awesome, looking forward to that.

by the way, I've test these lines and they do not work:

```elisp
(evil-define-text-object evil-inner-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count nil))

(evil-define-text-object evil-a-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count t))
```

no test object is even created. `ci|` does nothing.

**Comment by noctuid** [comment] 2016-11-30 18:05
Are you sure? Did you bind them?:
```
(define-key evil-inner-text-objects-map "|" #'evil-inner-pipe)
(define-key evil-outer-text-objects-map "|" #'evil-a-pipe)
```

**Comment by ninrod** [comment] 2016-11-30 18:09
oh god. I'm such a noob. of course I did not bind them. It is working flawlessly. Almost magical.

**Comment by ninrod** [comment] 2016-12-05 02:00
@noctuid, in this sample, cursor is on [|]

Using this configuration:

```elisp
(evil-define-text-object evil-inner-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count nil))

(evil-define-text-object evil-a-pipe  (count &optional beg end type)
  (evil-select-quote ?\| beg end type count t))
```

and applying `ci|` in this sample

```txt
| foo | [b]ar |
| baz |       |
```

gives me this (insert-mode):

```txt
| foo | bar |[]| baz |       |
```

seems that seeking is behaving a bit to eager when using this hack.

**Comment by noctuid** [comment] 2016-12-05 04:08
The problem is that `evil-select-quote` is meant for balanced quotes, and tables don't have a balanced number of pipes. I'm going to have the "separator" type text object which will be better for this in my port of the targets plugin. I've already basically implemented this and the other types, but I haven't had any time to work on it since that day. I ran into a problem with how evil handles delimiters in quotes (`evil-up-block` isn't as smart as it could be) that I want to fix first, but I'll probably publish a basic implementation sometime this week. It may be a few weeks before I write all the necessary tests and polish it more though.

Anyway, since I'm going to obsolete this plugin, I'm going to go ahead and close this issue. If you have any other questions/suggestions, feel free to post an issue [here](https://github.com/noctuid/targets.el).

**Closed as completed by noctuid** 2016-12-05 04:08 UTC
Labels: bug

**Comment by noctuid** [comment] 2016-12-05 04:19
To clarify a little, if you replace the pipes with quotes, the jump forward makes sense because `bar` is not in a quote.

**Comment by ninrod** [comment] 2016-12-05 11:08
@noctuid yes!, that makes sense indeed. Ok, awesome, I'll post new issues there.

**Comment by noctuid** [comment] 2016-12-18 04:12
I committed the basic functionality to targets.el. I just had a decent chunk of free time, so I was able to write some tests as well. There's no documentation yet, but here are some notes if you want to try it:

- `targets-define-to` is used to generate the targets text objects (`i`, `a`, `I`, `A`, and the `n` and `l` versions of these)
- the "types" of text objects it can create are pair, quote, separator, and object
- targets.vim doesn't have the equivalent of an "object" currently; it is a thing (as in thingatpt.el) like `evil-word` or `evil-sentence`
- `(targets-setup t)` can be used to define and bind over all of evil's default text objects (it doesn't bind objects yet; see `targets-text-objects`)
- I decided to ignore evil's seeking entirely and allow for customizable seeking like in targets.vim (see `targets-seek-functions`); by default text objects will seek forward and then backward with no bounds
- Addition to the jump list when seeking is also customizable by either customizing the seek functions or redefining `targets-push-jump-p`

Not implemented yet but planned:
- a simple way to bound seeking without redefining any functions
- the simpler text object definer from this issue (just defines inner and outer and supports `evil-range`)
- composite text object definer (anyblock and expand-region functionality)
- remote text objects (allows remote use like `n`/`l`, but select the text object with avy instead of a count)
- a few extra simple text objects (line, buffer, generic quote as composite text object, etc.)
- object text objects have not been tested at all yet and probably don't work as they should

If you do test it, any feedback is appreciated.

On a side note, the problem with the earlier code and the text objects not being visible was that it uses `make-symbol` and should use `intern` instead.

**Comment by ninrod** [comment] 2016-12-18 16:09
AWESOME! Ok I'll test and place my fidings there! Thanks!
